version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "nodejs/package.json" }}
      - run:
          name: install-node-dependencies
          command: cd nodejs && npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "nodejs/package.json" }}
          paths:
            - ./nodejs/node_modules
      - run: # run tests
          name: run npm test
          command: cd nodejs && npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: nodejs/reports/junit
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: nodejs/coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: nodejs/reports/junit
      - run:
          name: package the output
          command: cd nodejs && npm run pack
      - run:
          name: create build directory
          command: mkdir -p nodejs/build
      - run:
          name: copy output to a file with the branchname
          command: mv nodejs/$(cat package.json | jq -r '.name').zip nodejs/build/$LAMBDA_FUNCTION_NAME.$CIRCLE_BRANCH.zip
      - run: ls -alh nodejs/
      - persist_to_workspace:
          root: nodejs/build
          paths:
            - "*.zip"
      - run:
          name: Clean up
          command: cd nodejs && npm run cleanup
  aws-cli:
    executor:
      name: aws-cli/default
      python-version: "3.5"
    steps:
      - attach_workspace:
          at: /tmp/nodejs/build
      - aws-cli/install
      - aws-cli/configure:
          profile-name: example
      - run: |
          if [[ ! -z $LAMBDA_S3_BUCKET_NAME ]]; then
            $(aws s3api head-bucket --bucket $LAMBDA_S3_BUCKET_NAME);
            if [[ $? == 0 ]]; then
               aws s3 cp /tmp/nodejs/build/$LAMBDA_FUNCTION_NAME.$CIRCLE_BRANCH.zip s3://$LAMBDA_S3_BUCKET_NAME/$LAMBDA_S3_PREFIX$LAMBDA_FUNCTION_NAME.$CIRCLE_BRANCH.zip
            else
               echo "bucket does not exist or permission is not there to view it."
            fi
          fi
workflows:
  version: 2
  build-CloudFrontJWTValidator:
    jobs:
      - build
      - aws-cli:
          requires:
            - build
          context: aws
